model:
  model_type: "autoregressive"
  img_channel: 1
  num_channels: 128
  num_layers: 5

data:
  data_type: "mnist"
  batch_size: 64
  num_workers: 4

train:
  num_epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
