model_type: "autoregressive"
module_config:
  img_channel: 1
  num_channels: 64
  num_layers: 8
data:
  batch_size: 64
  num_workers: 4
train:
  num_epochs: 25
  learning_rate: 0.001
  optimizer: "adam"
